name: Release a new version of Contacty

on:
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
            java-version: 17
      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 17
          distribution: zulu
          server-id: github
          server-username: GITHUB_USER_REF
          server-password: GITHUB_TOKEN_REF
          cache: 'maven'
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Publish JAR
        run: mvn -B -Pgithub release:prepare release:perform --file pom.xml
        env:
          GITHUB_USER_REF: ${{secrets.GH_PACKAGE_REPO_USERNAME}}
          GITHUB_TOKEN_REF: ${{secrets.GH_PACKAGE_REPO_PASSWORD}}